### Send Message by User Test
POST http://localhost:4000/message-api/send/69b79c76c5222bee1869b061
Content-Type: application/json

{
    "sender":"69b79620be2d5cafc3939044",
    "content": "Hi This is the First Message"
}
### Get Messages

GET http://localhost:4000/message-api/messages/69b79c76c5222bee1869b061