### Send Message by User Test
POST http://40.0.54.132:4000/message-api/send
Content-Type: application/json

{
    "sender":"69b79620be2d5cafc3939044",
    "receiver":"69b79c76c5222bee1869b061",
    "content": "Hi This is the second Message"
}
### Get Messages

GET http://localhost:4000/message-api/messages/69b79c76c5222bee1869b061


### register
POST http://localhost:4000/user-api/register
Content-Type: application/json

{
    "name": "test",
    "email": "test@gmail.com",
    "password": "test123"
}

### login
POST http://localhost:4000/user-api/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test1234"
}

### change password
PATCH http://localhost:4000/user-api/change-password
Content-Type: application/json

{
    "email": "test2@gmail.com",
    "currentPassword": "test123",
    "newPassword": "test1234"
}